"""Generate additive structure rewards without overriding source loot tables."""
import json
from build import read, require, identifier

def compile_structure_script(root):
    coverage = read(root / 'structure-routes.json')
    profiles = read(root / 'structure-rewards.json')
    evidence = set(read(root / 'structure-item-evidence.json'))
    seen = set()
    for name, profile in profiles.items():
        require(type(profile['chance']) in (float, int) and 0 <= profile['chance'] <= 1, f'Invalid chance: {name}')
        require(bool(profile['items']), f'Empty rewards: {name}')
        items = set()
        for entry in profile['items']:
            item = identifier(entry['item'])
            require(item not in items, f'Duplicate reward: {item}')
            items.add(item)
            require(item in evidence, f'No installed item evidence: {item}')
            require(not item.startswith(('beachparty:', 'phomesteadplushies:', 'perfectplushies:')), f'Overlapping collectible route: {item}')
            require(type(entry['count']) is int and 1 <= entry['count'] <= 64, f'Invalid count: {item}')
            require(type(entry['weight']) is int and entry['weight'] > 0, f'Invalid weight: {item}')
    excluded = {row['target'] for row in coverage['excluded']}
    for row in coverage['routes']:
        target = identifier(row['target'])
        require(target not in seen and target not in excluded, f'Duplicate/nested target: {target}')
        seen.add(target)
        require(row['profile'] in profiles, f'Unknown structure profile: {target}')
    targets = [{'target': r['target'], 'profile': r['profile']} for r in coverage['routes']]
    return ('// Generated by loot-workshop/build.py. Edit structure-rewards.json and structure-routes.json.\n'
        'ServerEvents.chestLootTables(event => {\n'
        '  const profiles = ' + json.dumps(profiles, indent=2) + ';\n'
        '  const routes = ' + json.dumps(targets, indent=2) + ';\n'
        '  routes.forEach(route => event.modify(route.target, loot => {\n'
        '    const profile = profiles[route.profile];\n'
        '    loot.addPool(pool => {\n'
        '      pool.rolls = 1;\n'
        '      pool.addCondition({condition: "minecraft:random_chance", chance: profile.chance});\n'
        '      profile.items.forEach(entry => pool.addItem(Item.of(entry.item, entry.count), entry.weight));\n'
        '    });\n'
        '  }));\n'
        '});\n').encode('utf-8')
