name = "True Bastard ModPack"
author = "Moonie"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15353147b5d8715e0479b91359c9b7ce1b2031f5b50fdbc704b9f6788c62cb6a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
