name = "True Bastard ModPack"
author = "Moonie"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e963d87e33b19206d136bb0046af43f1b03b1b0a296e0b6ac15e24d328d98110"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
