name = "True Bastard ModPack"
author = "Moonie"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aced733c438d2cee3f7f3499a77aff9187827c8e1747f959cdaac54cceaa7b03"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
