{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "tiny-remapper",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-remapper-0.13.0.jar",
          "url": "tiny-remapper-0.13.0.jar",
          "size": 235288,
          "sha512": "99f9dbf5afc9ed0614cdeea26ced4a1a389557626aa5a3ac7c4334e749ad04012003e4a21d8009aeafc770df6130552205d07960a42e5b782c8be1d70a521359",
          "sha256": "21b83bbf32494519e1862c7eb50b720b63ed07171d6c5a6e892d0eef8512a203",
          "sha1": "563be2546650b5ba882544aa391a9b66109044f1",
          "md5": "5f33857d82f8ee5bbc8de87b5a65de65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "tiny-remapper-0.13.0.jar",
          "url": "tiny-remapper-0.13.0.jar",
          "size": 235288,
          "sha512": "99f9dbf5afc9ed0614cdeea26ced4a1a389557626aa5a3ac7c4334e749ad04012003e4a21d8009aeafc770df6130552205d07960a42e5b782c8be1d70a521359",
          "sha256": "21b83bbf32494519e1862c7eb50b720b63ed07171d6c5a6e892d0eef8512a203",
          "sha1": "563be2546650b5ba882544aa391a9b66109044f1",
          "md5": "5f33857d82f8ee5bbc8de87b5a65de65"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-remapper-0.13.0-fat.jar",
          "url": "tiny-remapper-0.13.0-fat.jar",
          "size": 827693,
          "sha512": "6449007382735dbc0696918b01dbc0a34bed63a3de89954894969cb32724015a10f13e7d79f64cf431bea588be89b27afae750f97d511fef61a56799f815f3ba",
          "sha256": "20fd9e980a6eeba4b6f876a3b0601fce8c1c8a006fff0c2950978774fe81717f",
          "sha1": "79976d040a9151c91fb82fb9b560ea7df6306413",
          "md5": "b58e7d0a0dd03353b2cad3767fefe266"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-remapper-0.13.0-sources.jar",
          "url": "tiny-remapper-0.13.0-sources.jar",
          "size": 131954,
          "sha512": "657c9474f20c6826b7de0ec66ca57d41fa878cb5acd0ad0c765ac63e8cb60812f8ea2164adc03b103b39eb9d0e7e261e259349cd94ed44ad32905bde580abb3d",
          "sha256": "dc1f8bdf9d29b012456adde49c21db2719c404593b4334dc9872fc5aa7383784",
          "sha1": "263ff9213197074dc9026bd5709758a48d7b01cc",
          "md5": "2cfa81d3c3a68757738d7c820bc2c07b"
        }
      ]
    }
  ]
}
