{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.16.3.jar",
          "url": "fabric-loom-1.16.3.jar",
          "size": 1385765,
          "sha512": "b1c944cbd888fd7adf26d0ba1d772f27ed014d80f48976d889be0c5cdb36ae9ce3115db54c576821d1cfed9412e3b82cf11b01eb93569903e9f175e7831d29b4",
          "sha256": "653d6483b5b54508b153f4d79edc0d9e97d0b9aaa03efe23b6f9884ab4b571fa",
          "sha1": "64d19d778f345ab59c1630a50d77815a8f400b46",
          "md5": "05be689b94aab64a4fc55d72d50f584e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.4.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.16.3.jar",
          "url": "fabric-loom-1.16.3.jar",
          "size": 1385765,
          "sha512": "b1c944cbd888fd7adf26d0ba1d772f27ed014d80f48976d889be0c5cdb36ae9ce3115db54c576821d1cfed9412e3b82cf11b01eb93569903e9f175e7831d29b4",
          "sha256": "653d6483b5b54508b153f4d79edc0d9e97d0b9aaa03efe23b6f9884ab4b571fa",
          "sha1": "64d19d778f345ab59c1630a50d77815a8f400b46",
          "md5": "05be689b94aab64a4fc55d72d50f584e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.16.3-sources.jar",
          "url": "fabric-loom-1.16.3-sources.jar",
          "size": 829812,
          "sha512": "4617299d4b2faff1f0ec1dbb0e87ebbb54deb3ba95e41c31a7b0eb2b1fed341f6518b402166b6288ca4b90bb020fc592c22467a44a2bf7043da8423b0136792c",
          "sha256": "866b920a6108c1ef7e45c954ce7adc1340429c6f20bb08351870456ef66e488c",
          "sha1": "28c61e6c81f469ef34f723b763f593c7e87f626a",
          "md5": "aec87fb10e7c30e3906187de92d3a04f"
        }
      ]
    }
  ]
}
