org.gradle.jvmargs=-Xmx2G
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
fabric_version=0.92.12+1.20.1
lootr_jar=I:/PrismLauncher/instances/MS Test Client/minecraft/mods/lootr-fabric-1.20-0.7.35.86.jar
mod_version=0.2.0
maven_group=forcedrelocation
archives_base_name=forced-relocation-loot-tidy
