// Generated by loot-workshop/build.py. Edit structure-rewards.json and structure-routes.json.
ServerEvents.chestLootTables(event => {
  const profiles = {
  "village": {
    "chance": 0.6,
    "items": [
      {
        "item": "farmersdelight:onion",
        "count": 3,
        "weight": 5
      },
      {
        "item": "farmersdelight:tomato_seeds",
        "count": 2,
        "weight": 4
      },
      {
        "item": "farmersdelight:canvas",
        "count": 2,
        "weight": 3
      },
      {
        "item": "create:copper_sheet",
        "count": 2,
        "weight": 2
      },
      {
        "item": "farmersdelight:chicken_soup",
        "count": 1,
        "weight": 2
      },
      {
        "item": "farm_and_charm:barley_seeds",
        "count": 2,
        "weight": 3
      },
      {
        "item": "hexalia:lavender",
        "count": 2,
        "weight": 2
      },
      {
        "item": "brewery:beer_hops",
        "count": 2,
        "weight": 2
      }
    ]
  },
  "easy": {
    "chance": 0.5,
    "items": [
      {
        "item": "create:raw_zinc",
        "count": 3,
        "weight": 5
      },
      {
        "item": "create:andesite_alloy",
        "count": 2,
        "weight": 4
      },
      {
        "item": "farmersdelight:canvas",
        "count": 2,
        "weight": 3
      },
      {
        "item": "farmersdelight:cooked_bacon",
        "count": 3,
        "weight": 3
      },
      {
        "item": "create:copper_sheet",
        "count": 2,
        "weight": 3
      },
      {
        "item": "create:zinc_ingot",
        "count": 2,
        "weight": 3
      },
      {
        "item": "farm_and_charm:lettuce_seeds",
        "count": 2,
        "weight": 3
      },
      {
        "item": "hexalia:mandrake_seeds",
        "count": 1,
        "weight": 2
      },
      {
        "item": "brewery:beer_mug",
        "count": 1,
        "weight": 2
      }
    ]
  },
  "medium": {
    "chance": 0.65,
    "items": [
      {
        "item": "create:andesite_alloy",
        "count": 4,
        "weight": 5
      },
      {
        "item": "create:copper_sheet",
        "count": 3,
        "weight": 4
      },
      {
        "item": "create:brass_ingot",
        "count": 2,
        "weight": 2
      },
      {
        "item": "farmersdelight:beef_stew",
        "count": 1,
        "weight": 3
      },
      {
        "item": "farmersdelight:rope",
        "count": 4,
        "weight": 3
      },
      {
        "item": "create:zinc_ingot",
        "count": 3,
        "weight": 3
      },
      {
        "item": "farm_and_charm:nettle_tea",
        "count": 1,
        "weight": 2
      },
      {
        "item": "hexalia:celestial_crystal",
        "count": 1,
        "weight": 1
      },
      {
        "item": "brewery:beer_wheat",
        "count": 1,
        "weight": 2
      }
    ]
  },
  "hard": {
    "chance": 0.8,
    "items": [
      {
        "item": "create:brass_ingot",
        "count": 4,
        "weight": 5
      },
      {
        "item": "create:precision_mechanism",
        "count": 1,
        "weight": 1
      },
      {
        "item": "farmersdelight:roast_chicken_block",
        "count": 1,
        "weight": 3
      },
      {
        "item": "create:experience_nugget",
        "count": 4,
        "weight": 4
      },
      {
        "item": "create:golden_sheet",
        "count": 3,
        "weight": 3
      },
      {
        "item": "hexalia:hex_focus",
        "count": 1,
        "weight": 1
      },
      {
        "item": "create:copper_diving_helmet",
        "count": 1,
        "weight": 1
      }
    ]
  },
  "water": {
    "chance": 0.6,
    "items": [
      {
        "item": "farmersdelight:fish_stew",
        "count": 1,
        "weight": 4
      },
      {
        "item": "farmersdelight:rope",
        "count": 5,
        "weight": 5
      },
      {
        "item": "create:copper_sheet",
        "count": 3,
        "weight": 4
      },
      {
        "item": "create:zinc_ingot",
        "count": 3,
        "weight": 3
      },
      {
        "item": "farmersdelight:canvas",
        "count": 3,
        "weight": 3
      },
      {
        "item": "oceansdelight:guardian_soup",
        "count": 1,
        "weight": 2
      },
      {
        "item": "brewery:beer_mug",
        "count": 1,
        "weight": 2
      }
    ]
  },
  "nether": {
    "chance": 0.65,
    "items": [
      {
        "item": "nethersdelight:hoglin_loin",
        "count": 3,
        "weight": 4
      },
      {
        "item": "nethersdelight:propelpearl",
        "count": 3,
        "weight": 4
      },
      {
        "item": "create:golden_sheet",
        "count": 3,
        "weight": 3
      },
      {
        "item": "create:brass_ingot",
        "count": 3,
        "weight": 3
      },
      {
        "item": "create:experience_nugget",
        "count": 3,
        "weight": 3
      },
      {
        "item": "hexalia:brew_of_bloodlust",
        "count": 1,
        "weight": 1
      }
    ]
  },
  "end": {
    "chance": 0.75,
    "items": [
      {
        "item": "betterend:crystal_shards",
        "count": 3,
        "weight": 4
      },
      {
        "item": "ends_delight:chorus_fruit_pie_slice",
        "count": 2,
        "weight": 4
      },
      {
        "item": "create:experience_nugget",
        "count": 6,
        "weight": 5
      },
      {
        "item": "create:precision_mechanism",
        "count": 1,
        "weight": 1
      },
      {
        "item": "create:brass_ingot",
        "count": 4,
        "weight": 4
      },
      {
        "item": "farmersdelight:stuffed_potato",
        "count": 3,
        "weight": 3
      },
      {
        "item": "ends_delight:chorus_fruit_wine",
        "count": 1,
        "weight": 2
      },
      {
        "item": "hexalia:celestial_crystal",
        "count": 2,
        "weight": 1
      }
    ]
  }
};
  const routes = [
  {
    "target": "betterdeserttemples:chests/food_storage",
    "profile": "village"
  },
  {
    "target": "betterdeserttemples:chests/lab",
    "profile": "easy"
  },
  {
    "target": "betterdeserttemples:chests/library",
    "profile": "medium"
  },
  {
    "target": "betterdeserttemples:chests/pharaoh_hidden",
    "profile": "medium"
  },
  {
    "target": "betterdeserttemples:chests/pot",
    "profile": "easy"
  },
  {
    "target": "betterdeserttemples:chests/statue",
    "profile": "easy"
  },
  {
    "target": "betterdeserttemples:chests/storage",
    "profile": "easy"
  },
  {
    "target": "betterdeserttemples:chests/tomb",
    "profile": "easy"
  },
  {
    "target": "betterdeserttemples:chests/tomb_pharaoh",
    "profile": "medium"
  },
  {
    "target": "betterdeserttemples:chests/wardrobe",
    "profile": "easy"
  },
  {
    "target": "betterdungeons:skeleton_dungeon/chests/common",
    "profile": "easy"
  },
  {
    "target": "betterdungeons:skeleton_dungeon/chests/middle",
    "profile": "easy"
  },
  {
    "target": "betterdungeons:small_dungeon/chests/loot_piles",
    "profile": "village"
  },
  {
    "target": "betterdungeons:small_nether_dungeon/chests/common",
    "profile": "nether"
  },
  {
    "target": "betterdungeons:spider_dungeon/chests/egg_room",
    "profile": "easy"
  },
  {
    "target": "betterdungeons:zombie_dungeon/chests/common",
    "profile": "easy"
  },
  {
    "target": "betterdungeons:zombie_dungeon/chests/special",
    "profile": "medium"
  },
  {
    "target": "betterdungeons:zombie_dungeon/chests/tombstone",
    "profile": "easy"
  },
  {
    "target": "betterfortresses:chests/beacon",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/extra",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/hall",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/keep",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/obsidian",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/puzzle",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/quarters",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/storage",
    "profile": "nether"
  },
  {
    "target": "betterfortresses:chests/worship",
    "profile": "nether"
  },
  {
    "target": "betterjungletemples:chests/campsite",
    "profile": "easy"
  },
  {
    "target": "betterjungletemples:chests/treasure",
    "profile": "medium"
  },
  {
    "target": "betteroceanmonuments:chests/upper_side_chamber",
    "profile": "water"
  },
  {
    "target": "betterstrongholds:chests/armoury",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/cmd_yung",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/common",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/crypt",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/grand_library",
    "profile": "medium"
  },
  {
    "target": "betterstrongholds:chests/library_md",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/mess",
    "profile": "village"
  },
  {
    "target": "betterstrongholds:chests/prison_lg",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/trap",
    "profile": "easy"
  },
  {
    "target": "betterstrongholds:chests/treasure",
    "profile": "medium"
  },
  {
    "target": "betterwitchhuts:chests/hut_0",
    "profile": "easy"
  },
  {
    "target": "ctov:chests/village/village_badlands_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_bakery",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_beach_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_dark_forest_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_forager",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_jungle_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_library",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_mountain_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_mushroom_house",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_smith",
    "profile": "village"
  },
  {
    "target": "ctov:chests/village/village_swamp_house",
    "profile": "village"
  },
  {
    "target": "imst:airship",
    "profile": "easy"
  },
  {
    "target": "imst:balloon",
    "profile": "easy"
  },
  {
    "target": "imst:bandit_camp",
    "profile": "easy"
  },
  {
    "target": "imst:beehouse",
    "profile": "village"
  },
  {
    "target": "imst:berry_house",
    "profile": "village"
  },
  {
    "target": "imst:cactus_farm",
    "profile": "village"
  },
  {
    "target": "imst:caravan",
    "profile": "village"
  },
  {
    "target": "imst:cocoa_farm",
    "profile": "village"
  },
  {
    "target": "imst:mountain_camp",
    "profile": "village"
  },
  {
    "target": "imst:sunflower_farm",
    "profile": "village"
  },
  {
    "target": "imst:train_station",
    "profile": "village"
  },
  {
    "target": "imst:witch_hut",
    "profile": "village"
  },
  {
    "target": "mes:end_common",
    "profile": "end"
  },
  {
    "target": "mes:end_rare",
    "profile": "end"
  },
  {
    "target": "mes:end_uncommon",
    "profile": "end"
  },
  {
    "target": "mes:mega_ship_barrel",
    "profile": "end"
  },
  {
    "target": "mes:mega_ship_barrel_empty",
    "profile": "end"
  },
  {
    "target": "mes:mega_ship_barrel_empty_rare",
    "profile": "end"
  },
  {
    "target": "mes:mega_ship_crate",
    "profile": "end"
  },
  {
    "target": "mes:mega_ship_treasure",
    "profile": "end"
  },
  {
    "target": "minecraft:chests/illager_mansion/ancient_city_raid_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/evoker_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/generic",
    "profile": "village"
  },
  {
    "target": "minecraft:chests/illager_mansion/kitchen",
    "profile": "village"
  },
  {
    "target": "minecraft:chests/illager_mansion/library_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/map_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/pillager_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/ravager_chest",
    "profile": "village"
  },
  {
    "target": "minecraft:chests/illager_mansion/secret_room",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/smithing_room",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/vindicator_chest",
    "profile": "medium"
  },
  {
    "target": "minecraft:chests/illager_mansion/witch_chest",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/illager_mansion/wool",
    "profile": "easy"
  },
  {
    "target": "minecraft:chests/nether_fortress/fort_inside",
    "profile": "nether"
  },
  {
    "target": "minecraft:chests/nether_fortress/fort_inside_generic",
    "profile": "nether"
  },
  {
    "target": "minecraft:chests/village/village_jungle_house",
    "profile": "village"
  },
  {
    "target": "minecraft:chests/village/village_swamp_house",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_archer",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_blacksmith",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_cartographer",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_church",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_farm",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_house",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_librarian",
    "profile": "village"
  },
  {
    "target": "mmv:village_dark_oak_stonecutter",
    "profile": "village"
  },
  {
    "target": "mmv:village_jungle_house",
    "profile": "village"
  },
  {
    "target": "mmv:village_swamp_house",
    "profile": "village"
  },
  {
    "target": "mns:chests/dragon_arena/epic",
    "profile": "nether"
  },
  {
    "target": "mns:chests/dragon_arena/main_barrel",
    "profile": "nether"
  },
  {
    "target": "mns:chests/dragon_arena/mid",
    "profile": "nether"
  },
  {
    "target": "mns:chests/empty",
    "profile": "nether"
  },
  {
    "target": "mns:chests/houses",
    "profile": "nether"
  },
  {
    "target": "mns:chests/large_arena/common",
    "profile": "nether"
  },
  {
    "target": "mns:chests/large_arena/main_barrel",
    "profile": "nether"
  },
  {
    "target": "mns:chests/large_arena/treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/brewing_scraps",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact_base",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact_gold_treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact_library",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact_treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/intact_uncommon",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/ravaged",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/ravaged_treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/ruined",
    "profile": "nether"
  },
  {
    "target": "mns:chests/mega_fortress/tnt_room",
    "profile": "nether"
  },
  {
    "target": "mns:chests/small_arena/gold_treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/small_arena/mid",
    "profile": "nether"
  },
  {
    "target": "mns:chests/small_arena/rare",
    "profile": "nether"
  },
  {
    "target": "mns:chests/treasure",
    "profile": "nether"
  },
  {
    "target": "mns:chests/uncommon",
    "profile": "nether"
  },
  {
    "target": "mtr:badlands_temple_common",
    "profile": "village"
  },
  {
    "target": "mtr:badlands_temple_decorated_pot",
    "profile": "easy"
  },
  {
    "target": "mtr:badlands_temple_rare",
    "profile": "easy"
  },
  {
    "target": "mtr:desert_temple_crypt_chest",
    "profile": "medium"
  },
  {
    "target": "mtr:desert_temple_decorated_pot",
    "profile": "easy"
  },
  {
    "target": "mtr:desert_temple_lower_chamber",
    "profile": "easy"
  },
  {
    "target": "mtr:desert_temple_pillar_chest",
    "profile": "medium"
  },
  {
    "target": "mtr:desert_temple_wall_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:empty",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_corridor",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_crypt_barrel_empty",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_crypt_barrel_full",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_crypt_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_decorated_pot",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_lava_chamber",
    "profile": "medium"
  },
  {
    "target": "mtr:jungle_temple_main_common",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_main_double",
    "profile": "medium"
  },
  {
    "target": "mtr:jungle_temple_puzzle_treasure",
    "profile": "medium"
  },
  {
    "target": "mtr:jungle_temple_upper_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:jungle_temple_upper_double",
    "profile": "easy"
  },
  {
    "target": "mtr:nether_temple_common",
    "profile": "nether"
  },
  {
    "target": "mtr:nether_temple_rare",
    "profile": "nether"
  },
  {
    "target": "mtr:nether_temple_uncommon",
    "profile": "nether"
  },
  {
    "target": "mtr:ocean_temple_treasure",
    "profile": "water"
  },
  {
    "target": "mtr:stronghold_barracks_barrel",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_barracks_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_corridor_common",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_corridor_empty",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_corridor_rare",
    "profile": "medium"
  },
  {
    "target": "mtr:stronghold_corridor_uncommon",
    "profile": "medium"
  },
  {
    "target": "mtr:stronghold_decorated_pot",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_library_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_library_trapped_chest",
    "profile": "easy"
  },
  {
    "target": "mtr:stronghold_mossy_special",
    "profile": "easy"
  },
  {
    "target": "mvs:abandoned",
    "profile": "village"
  },
  {
    "target": "mvs:cart",
    "profile": "village"
  },
  {
    "target": "mvs:cartographer_tower",
    "profile": "village"
  },
  {
    "target": "mvs:cathedral_base",
    "profile": "village"
  },
  {
    "target": "mvs:cathedral_common",
    "profile": "village"
  },
  {
    "target": "mvs:cathedral_rare",
    "profile": "easy"
  },
  {
    "target": "mvs:crystal",
    "profile": "village"
  },
  {
    "target": "mvs:empty",
    "profile": "easy"
  },
  {
    "target": "mvs:floating_islands",
    "profile": "village"
  },
  {
    "target": "mvs:general",
    "profile": "village"
  },
  {
    "target": "mvs:houses_books",
    "profile": "village"
  },
  {
    "target": "mvs:houses_brewing",
    "profile": "easy"
  },
  {
    "target": "mvs:houses_common",
    "profile": "village"
  },
  {
    "target": "mvs:houses_desert",
    "profile": "village"
  },
  {
    "target": "mvs:houses_flower",
    "profile": "village"
  },
  {
    "target": "mvs:houses_rare",
    "profile": "easy"
  },
  {
    "target": "mvs:houses_uncommon",
    "profile": "village"
  },
  {
    "target": "mvs:jungle_tower",
    "profile": "village"
  },
  {
    "target": "mvs:large_carts",
    "profile": "village"
  },
  {
    "target": "mvs:large_carts_2",
    "profile": "village"
  },
  {
    "target": "mvs:mushroom_pond",
    "profile": "village"
  },
  {
    "target": "mvs:ocean_tower/common",
    "profile": "water"
  },
  {
    "target": "mvs:ocean_tower/treasure",
    "profile": "water"
  },
  {
    "target": "mvs:ocean_tower/uncommon",
    "profile": "water"
  },
  {
    "target": "mvs:pillager",
    "profile": "easy"
  },
  {
    "target": "mvs:pond",
    "profile": "easy"
  },
  {
    "target": "mvs:rare",
    "profile": "medium"
  },
  {
    "target": "mvs:red_tower/common",
    "profile": "easy"
  },
  {
    "target": "mvs:red_tower/treasure",
    "profile": "hard"
  },
  {
    "target": "mvs:red_tower/uncommon",
    "profile": "easy"
  },
  {
    "target": "mvs:stable",
    "profile": "easy"
  },
  {
    "target": "mvs:swamps",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/badland_miner_outpost",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/badland_miner_outpost_forge",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/badland_miner_outpost_towers",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/conduit_ruin/conduit_ruin_big",
    "profile": "water"
  },
  {
    "target": "nova_structures:chests/conduit_ruin/conduit_ruin_main",
    "profile": "water"
  },
  {
    "target": "nova_structures:chests/conduit_ruin/conduit_ruin_small",
    "profile": "water"
  },
  {
    "target": "nova_structures:chests/creeping_crypt/crypt_grave",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/creeping_crypt/crypt_hallway",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/desert_ruins/desert_ruin_grave",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/desert_ruins/desert_ruin_house",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/desert_ruins/desert_ruin_lesser_treasure",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/desert_ruins/desert_ruin_main_temple",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/firewatch_tower",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/food_supply",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/hamlet/hamlet",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/hamlet/hamlet_tresure",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/illager_camp",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/illager_hideout_heart_loot",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/illager_hideout_random",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/jungle_ruins/jungle_ruins_main_temple",
    "profile": "medium"
  },
  {
    "target": "nova_structures:chests/mangrove_witchhud",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/mining_supply",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/nether_port/nether_port_chest",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/nether_port/nether_port_supplies",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/nether_skeleton_tower/skeleton_tower_camp",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/nether_skeleton_tower/skeleton_tower_chest",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/nether_skeleton_tower/skeleton_tower_supply",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/piglin_outstation/outstation_generic",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/piglin_outstation/outstation_tower",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/piglin_outstation/outstation_treasure",
    "profile": "nether"
  },
  {
    "target": "nova_structures:chests/pillager_outpost_kitchen",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/pillager_outpost_treasure",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/ruin_loot_master",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/stray_fort_archer",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/stray_fort_loot_generic",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/stray_fort_tresure",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/tavern_quest",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/undead_crypts_grave",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/water_supply",
    "profile": "water"
  },
  {
    "target": "nova_structures:chests/witch_villa/bedroom",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/dirty_clothes",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/gardening",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/general_storage",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/kitchen",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/lab",
    "profile": "village"
  },
  {
    "target": "nova_structures:chests/witch_villa/library",
    "profile": "medium"
  },
  {
    "target": "nova_structures:chests/witch_villa/music_room",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/witch_villa/potion_brewing",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/witch_villa/pumpkin_room",
    "profile": "easy"
  },
  {
    "target": "nova_structures:chests/witch_villa/slime_room",
    "profile": "village"
  },
  {
    "target": "structory:harvest/graveyard",
    "profile": "easy"
  },
  {
    "target": "structory:harvest/graveyard2",
    "profile": "easy"
  },
  {
    "target": "structory:harvest/manor2/loot",
    "profile": "easy"
  },
  {
    "target": "structory:harvest/manor2/treasure",
    "profile": "easy"
  },
  {
    "target": "structory:harvest/old_manor/common",
    "profile": "village"
  },
  {
    "target": "structory:harvest/old_manor/treasure",
    "profile": "easy"
  },
  {
    "target": "structory:library/high",
    "profile": "easy"
  },
  {
    "target": "structory:library/junk",
    "profile": "village"
  },
  {
    "target": "structory:library/low",
    "profile": "village"
  },
  {
    "target": "structory:mood/badlands",
    "profile": "village"
  },
  {
    "target": "structory:mood/cave",
    "profile": "village"
  },
  {
    "target": "structory:mood/jungle",
    "profile": "village"
  },
  {
    "target": "structory:mood/miner",
    "profile": "village"
  },
  {
    "target": "structory:mood/mushroom",
    "profile": "village"
  },
  {
    "target": "structory:mood/ocean",
    "profile": "water"
  },
  {
    "target": "structory:mood/snowy",
    "profile": "village"
  },
  {
    "target": "structory:outcast/bandit/desert",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/bandit/desert_copper",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/boat/loot",
    "profile": "water"
  },
  {
    "target": "structory:outcast/farm_ruin",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/generic/miner",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/low",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/mine/loot",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/ruin/ruin",
    "profile": "easy"
  },
  {
    "target": "structory:outcast/settlement",
    "profile": "village"
  },
  {
    "target": "structory:ruin/ruin",
    "profile": "easy"
  },
  {
    "target": "structory:ruin/swamp/loot",
    "profile": "easy"
  },
  {
    "target": "structory:ruin/taiga/illager_high",
    "profile": "easy"
  },
  {
    "target": "structory:ruin/taiga/illager_low",
    "profile": "village"
  },
  {
    "target": "structory:ruin/taiga/illager_treasure",
    "profile": "easy"
  },
  {
    "target": "structory:ruin/taiga/loot",
    "profile": "easy"
  },
  {
    "target": "structory_towers:basic/ocean_pillar_basic",
    "profile": "water"
  },
  {
    "target": "structory_towers:basic/pillager_basic",
    "profile": "easy"
  },
  {
    "target": "structory_towers:end_tower",
    "profile": "end"
  },
  {
    "target": "structory_towers:sword_portal",
    "profile": "nether"
  },
  {
    "target": "structory_towers:toadstool",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/crimson_top",
    "profile": "nether"
  },
  {
    "target": "structory_towers:top/dark_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/desert_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/farm_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/forager_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/fortress_top",
    "profile": "nether"
  },
  {
    "target": "structory_towers:top/lighthouse_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/mangrove_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/nomad_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/ocean_pillar_top",
    "profile": "water"
  },
  {
    "target": "structory_towers:top/paranoid_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/pillager_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/sacred_temple_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/small_firetower_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/strange_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/trader_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/warped_top",
    "profile": "nether"
  },
  {
    "target": "structory_towers:top/wizard_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:top/workshop_top",
    "profile": "easy"
  },
  {
    "target": "structory_towers:workshop_minecart",
    "profile": "easy"
  },
  {
    "target": "yungsextras:desert/chillzone",
    "profile": "village"
  },
  {
    "target": "yungsextras:desert/ruins",
    "profile": "easy"
  }
];
  routes.forEach(route => event.modify(route.target, loot => {
    const profile = profiles[route.profile];
    loot.addPool(pool => {
      pool.rolls = 1;
      pool.addCondition({condition: "minecraft:random_chance", chance: profile.chance});
      profile.items.forEach(entry => pool.addItem(Item.of(entry.item, entry.count), entry.weight));
    });
  }));
});
