# ConstructionWand client config
# Press SNEAK+OPTKEY instead of SNEAK for opening wand GUI
requireOptKeyForMenu=true

# Press SNEAK+OPTKEY instead of SNEAK for changing wand mode/direction lock
requireOptKeyForActions=true

