#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 12:08:51 BST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=14
shaderPack=LOW ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
enableShaders=true
